openapi: 3.0.0
info:
  title: Trackier API v2
  version: '1.0'
  description: Trackier v2 API
  contact:
    name: Support
    url: 'https://trackier.com/support'
    email: support@trackier.com
servers:
  - url: 'https://api.trackier.com/'
paths:
  /v2/publishers:
    get:
      summary: Get All Publishers
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  publishers:
                    type: array
                    items:
                      $ref: '#/components/schemas/Publisher'
                  lastId:
                    type:
                      - number
                      - 'null'
              examples:
                example-1:
                  value:
                    publishers:
                      - region:
                          currency: USD
                          zone: Asia/Kolkata
                          lang: en
                          address: D-96 Flat no -112 5th Floor Munirika Village
                          city: New Delhi
                          zipcode: '110067'
                          country: IN
                        meta:
                          bank:
                            name: ''
                            ifsc: ''
                            account_no: ''
                            account_owner: ''
                          payout:
                            paypal: ''
                            payquicker: ''
                            payoneer: ''
                            paytm: alb_magji@hotmail.uk
                            mobicash: ''
                            easypaisa: ''
                          tdomain: []
                        tags:
                          - top publisher
                          - demo account
                        name: Pied Piper
                        email: subhomoy@trackier.com
                        country: IN
                        currency: INR
                        created: '2016-09-19T18:30:00.000Z'
                        modified: '2019-12-13T05:06:32.406Z'
                        username: '#PiedPiper'
                        phone: '8811576958'
                        login: '2017-10-28T06:27:06.000Z'
                        login_attempts: 1
                        manager_id: 5d25b773b6920d39cf195611
                        tier_id: 594400fa17c452060005e362
                        status: active
                        unsubscribe: false
                        signup_ip: 1.1.1.1
                        company: Pied piper
                        is_demo: false
                        macro:
                          source: '{aff_id}'
                          p1: '{transaction_id}'
                          p8: '{aff_sub8}'
                          p9: '{aff_sub9}'
                          p10: '{aff_sub10}'
                        hashId: 57c6c75934243d930c8b4581
                        id: 2
                        whitelistAdv: []
                        blockedSources:
                          - hemant_testing
                      - region:
                          currency: USD
                          zone: Asia/Kolkata
                          lang: en
                        meta:
                          payout:
                            paypal: ''
                            payquicker: ''
                            payoneer: ''
                            paytm: ''
                            mobicash: ''
                            easypaisa: ''
                        tags: []
                        name: test pub
                        email: sales@s2ssoftsys.in
                        country: IN
                        currency: INR
                        created: '2016-09-21T00:00:00.000Z'
                        modified: '2019-12-13T05:06:32.481Z'
                        username: test pub
                        phone: null
                        login: null
                        manager_id: 5d78cae3b6920d28be58cc1a
                        login_attempts: null
                        tier_id: null
                        status: deleted
                        unsubscribe: false
                        is_demo: false
                        macro:
                          p1: '{your-transaction-id}'
                          source: '{your-sub-aff-id}'
                        hashId: 57e262141d41c81f2b04b8d0
                        id: 5
                        whitelistAdv: []
                        blockedSources: []
      operationId: get-publishers
      description: Get all publishers
      parameters:
        - schema:
            type: string
          in: header
          name: x-api-key
          description: API Key required for authentication
          required: true
        - schema:
            type: string
          in: query
          name: lastId
          description: If lastId param is present in the request then we need to send this param in the request to get the next set of rows
    post:
      summary: Create a new publisher
      operationId: post-publishers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  publisher:
                    $ref: '#/components/schemas/Publisher'
              examples:
                example-1:
                  value:
                    publisher:
                      region:
                        currency: USD
                        zone: Asia/Kolkata
                        lang: en
                        address: D-96 Flat no -112 5th Floor Munirika Village
                        city: New Delhi
                        zipcode: '110067'
                        country: IN
                      meta:
                        bank:
                          name: ''
                          ifsc: ''
                          account_no: ''
                          account_owner: ''
                      tags:
                        - top publisher
                        - demo account
                      name: test pub
                      email: support@trackier.com
                      country: IN
                      currency: INR
                      created: '2016-09-19T18:30:00.000Z'
                      modified: '2019-12-13T05:06:32.406Z'
                      username: '#PiedPiper'
                      phone: '8811576958'
                      login: '2017-10-28T06:27:06.000Z'
                      login_attempts: 1
                      manager_id: 5d25b773b6920d39cf195611
                      tier_id: 594400fa17c452060005e362
                      status: active
                      unsubscribe: false
                      signup_ip: 1.1.1.1
                      company: Pied piper
                      is_demo: false
                      macro:
                        source: '{aff_id}'
                        p1: '{transaction_id}'
                        p8: '{aff_sub8}'
                        p9: '{aff_sub9}'
                        p10: '{aff_sub10}'
                      hashId: 57c6c75934243d930c8b4581
                      id: 2
                      whitelistAdv: []
                      blockedSources:
                        - hemant_testing
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        statusCode:
                          type: integer
                        code:
                          type: string
                        message:
                          type: string
                        codeMsg:
                          type: string
              examples:
                example-1:
                  value:
                    errors:
                      - statusCode: 400
                        code: '4002'
                        codeMsg: ValidationError
                        message: Please fill the required fields
      description: Create a new publisher
      parameters:
        - schema:
            type: string
          in: header
          name: x-api-key
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
            examples:
              example-1:
                value:
                  name: hemant
                  password: '12345566'
                  email: sdfsdf22@g.com
                  phone: '123456789'
                  username: '123'
                  company: Trackier api v2
                  customFields:
                    testing: '123'
                    country: IN
        description: Data to be sent to create a new publisher
    parameters: []
  '/v2/publishers/{id}':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
        description: Publisher ID
    get:
      summary: Find Publisher by ID
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  publisher:
                    $ref: '#/components/schemas/Publisher'
              examples:
                example-1:
                  value:
                    publisher:
                      region:
                        currency: USD
                        zone: Asia/Kolkata
                        lang: en
                        address: D-96 Flat no -112 5th Floor Munirika Village
                        city: New Delhi
                        zipcode: '110067'
                        country: IN
                      meta:
                        bank:
                          name: ''
                          ifsc: ''
                          account_no: ''
                          account_owner: ''
                      tags:
                        - top publisher
                        - demo account
                      name: test pub
                      email: support@trackier.com
                      country: IN
                      currency: INR
                      created: '2016-09-19T18:30:00.000Z'
                      modified: '2019-12-13T05:06:32.406Z'
                      username: '#PiedPiper'
                      phone: '8811576958'
                      login: '2017-10-28T06:27:06.000Z'
                      login_attempts: 1
                      manager_id: 5d25b773b6920d39cf195611
                      tier_id: 594400fa17c452060005e362
                      status: active
                      unsubscribe: false
                      signup_ip: 1.1.1.1
                      company: Pied piper
                      is_demo: false
                      macro:
                        source: '{aff_id}'
                        p1: '{transaction_id}'
                        p8: '{aff_sub8}'
                        p9: '{aff_sub9}'
                        p10: '{aff_sub10}'
                      hashId: 57c6c75934243d930c8b4581
                      id: 2
                      whitelistAdv: []
                      blockedSources:
                        - hemant_testing
      operationId: get-publishers-id
      description: Get a single publisher
      parameters:
        - schema:
            type: string
          in: header
          name: x-api-key
          required: true
    delete:
      summary: Delete a publisher
      operationId: delete-publishers-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
              examples:
                example-1:
                  value:
                    success: true
                    message: 'Publisher Removed!'
      description: Delete a publisher with given ID
      parameters:
        - schema:
            type: string
          in: header
          name: x-api-key
          required: true
    post:
      summary: Edit a publisher
      operationId: post-publishers-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  publisher:
                    $ref: '#/components/schemas/Publisher'
              examples:
                example-1:
                  value:
                    publisher:
                      region:
                        currency: USD
                        zone: Asia/Kolkata
                        lang: en
                        address: D-96 Flat no -112 5th Floor Munirika Village
                        city: New Delhi
                        zipcode: '110067'
                        country: IN
                      meta:
                        bank:
                          name: ''
                          ifsc: ''
                          account_no: ''
                          account_owner: ''
                        payout:
                          paypal: ''
                          payquicker: ''
                          payoneer: ''
                          paytm: alb_magji@hotmail.uk
                          mobicash: ''
                          easypaisa: ''
                        tdomain: []
                      tags:
                        - top publisher
                        - demo account
                      name: Pied Piper
                      email: subhomoy@trackier.com
                      country: IN
                      currency: INR
                      created: '2016-09-19T18:30:00.000Z'
                      modified: '2019-12-13T05:06:32.406Z'
                      username: '#PiedPiper'
                      phone: '8811576958'
                      login: '2017-10-28T06:27:06.000Z'
                      login_attempts: 1
                      manager_id: 5d25b773b6920d39cf195611
                      tier_id: 594400fa17c452060005e362
                      status: active
                      unsubscribe: false
                      signup_ip: 1.1.1.1
                      company: Pied piper
                      is_demo: false
                      macro:
                        source: '{aff_id}'
                        p1: '{transaction_id}'
                        p8: '{aff_sub8}'
                        p9: '{aff_sub9}'
                        p10: '{aff_sub10}'
                      hashId: 57c6c75934243d930c8b4581
                      id: 2
                      whitelistAdv: []
                      blockedSources:
                        - hemant_testing
      description: Edit a publisher
      parameters:
        - schema:
            type: string
          in: header
          name: x-api-key
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserEdit'
            examples:
              example-1:
                value:
                  name: himanshu4
                  status: active
          application/xml:
            schema:
              type: object
              properties: {}
        description: Properties to be sent in request
  /v2/advertisers:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  advertisers:
                    type: array
                    items:
                      $ref: '#/components/schemas/Advertiser'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/Error'
      operationId: get-v2-advertisers
    post:
      summary: ''
      operationId: post-v2-advertisers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  advertiser:
                    $ref: '#/components/schemas/Advertiser'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
  '/v2/advertisers/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  advertiser:
                    $ref: '#/components/schemas/Advertiser'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/Error'
      operationId: get-v2-advertisers-id
    post:
      summary: ''
      operationId: post-v2-advertisers-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  advertiser:
                    $ref: '#/components/schemas/Advertiser'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Advertiser'
            examples:
              example-1: {}
    delete:
      summary: ''
      operationId: delete-v2-advertisers-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/Error'
      parameters:
        - schema:
            type: string
          in: query
          name: '{id}'
components:
  schemas:
    Publisher:
      title: Publisher
      type: object
      x-examples:
        sample publisher object:
          tags:
            - hemant
          name: account
          email: hemant@vnative.com
          phone: '9999885566'
          region:
            currency: USD
            lang: en
          created: '2017-08-29T11:05:15.000Z'
          unsubscribe: false
          status: active
          modified: '2019-12-13T05:06:34.030Z'
          manager_id: 5c6e4af3b6920d6a02002f53
          username: vNative Account
          tier_id: 5943b5d6b6920d248f26fd37
          login: null
          login_attempts: null
          signup_ip: null
          company: vNative Account
          is_demo: false
          hide_camp: null
          macro:
            source: hemant
            p1: test
          hashId: 59a54a6b89d4465afb339a32
          id: 31
          whitelistAdv: null
          blockedSources:
            - hemant_testing
            - p1
            - p2
          conversionsPending: null
      properties:
        id:
          type: integer
        username:
          type: string
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        login:
          type: string
        currency:
          type: string
        region:
          type: object
          properties:
            currency:
              type: string
            lang:
              type: string
            country:
              type: string
            address:
              type: string
            city:
              type: string
            state:
              type: string
            zipcode:
              type: string
        tags:
          type: array
          items:
            type: string
        signup_ip:
          type: string
        company:
          type: string
        status:
          type: string
        meta:
          type: object
          properties:
            afields:
              type: object
            bank:
              type: object
              properties:
                name:
                  type: string
                ifsc:
                  type: string
                account_no:
                  type: string
                account_owner:
                  type: string
        hashId:
          type: string
        manager_id:
          type: string
        tier_id:
          type: string
        unsubscribe:
          type: string
        is_demo:
          type: string
        whitelistAdv:
          type: array
          items:
            type: integer
        macro:
          type: object
          properties:
            p1:
              type: string
            p2:
              type: string
            p3:
              type: string
            p4:
              type: string
            p5:
              type: string
            p6:
              type: string
            p7:
              type: string
            p8:
              type: string
            p9:
              type: string
            p10:
              type: string
            source:
              type: string
            app_name:
              type: string
            app_id:
              type: string
            gaid:
              type: string
        blockedSources:
          type: array
          items:
            type: string
        conversionsPending:
          type: integer
        created:
          type: string
        modified:
          type: string
    Advertiser:
      title: Advertiser
      type: object
      properties:
        id:
          type: number
        hashId:
          type: string
        username:
          type: string
        email:
          type: string
        phone:
          type: string
        login:
          type: string
        login_attempts:
          type: integer
        currency:
          type: string
        region:
          type: object
          properties:
            currency:
              type: string
            lang:
              type: string
            country:
              type: string
            address:
              type: string
            city:
              type: string
            state:
              type: string
            zipcode:
              type: string
        tags:
          type: array
          items:
            type: string
        signup_ip:
          type: string
        company:
          type: string
        status:
          type: string
        meta:
          type: object
          properties:
            afields:
              type: object
            security_token:
              type: string
        fallbackUrl:
          type: string
        blockedPubs:
          type: array
          items:
            type: number
        created:
          type: string
        modified:
          type: string
        redirectType:
          type: string
      x-examples:
        sample advertiser object:
          tags: null
          blocked_pubs: null
          name: Demo Advertiser
          email: inf@vnative.com
          currency: INR
          meta:
            security_token: b50346a1c529c82dac33
          created: '1970-01-01T00:00:00.000Z'
          modified: '2019-10-17T18:32:59.608Z'
          username: Vnative
          phone: '998855644'
          region:
            currency: USD
            lang: en
            country: ''
          login: '2017-10-30T08:39:27.000Z'
          login_attempts: null
          signup_ip: null
          status: active
          company: Demo
          unique_conv_ip: '0'
          check_links: null
          fallback_url: 'http://vnative.com/advertiser-fallback-url2?utm_source={publisher_id}&amp;utm_campaign={camp_id}&amp;utm_traffic={publisher_id}_{source}'
          redirect_type: '302'
          hashId: 57c4738434243dc57d8b456d
          id: 3
    Error:
      title: Error
      type: object
      properties:
        statusCode:
          type: integer
        code:
          type: string
        codeMsg:
          type: string
        message:
          type: string
      x-examples:
        error code sample:
          statusCode: 400
          code: '101'
          codeMsg: API_KEY_MISSING
          message: API Key is not found in request headers or query params
    UserCreate:
      title: UserCreate
      type: object
      description: ''
      properties:
        username:
          type: string
        name:
          type: string
        email:
          type: string
        password:
          type: string
        company:
          type: string
        phone:
          type: string
        country:
          type: string
        status:
          type: string
          enum:
            - active
            - pending
            - disabled
        region:
          type: object
          properties:
            lang:
              type: string
            currency:
              type: string
            address:
              type: string
            city:
              type: string
            state:
              type: string
            zipcode:
              type: string
        customFields:
          type: object
      required:
        - name
        - email
        - password
      x-examples:
        user create sample:
          name: Hemant
          email: hemant@gmail.com
          password: '12345678'
    UserEdit:
      title: UserEdit
      type: object
      properties:
        username:
          type: string
        name:
          type: string
        password:
          type: string
        email:
          type: string
        company:
          type: string
        phone:
          type: string
        country:
          type: string
        status:
          type: string
          enum:
            - active
            - pending
            - disabled
        region:
          type: object
          properties:
            lang:
              type: string
            currency:
              type: string
            country:
              type: string
            address:
              type: string
            state:
              type: string
            city:
              type: string
            zipcode:
              type: string
        customFields:
          type: object
      x-examples:
        user edit example:
          name: Hemant
          status: pending
  securitySchemes:
    API Key:
      name: API Key Param
      type: apiKey
      in: query
