openapi: 3.0.0
info:
  title: Trackier API v2
  version: '1.0'
  description: Trackier v2 API
  contact:
    name: Support
    url: 'https://trackier.com/support'
    email: support@trackier.com
servers:
  - url: 'https://api.trackier.com/'
paths:
  /v2/publishers:
    get:
      summary: Find All Publishers
      tags:
        - Publishers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  publishers:
                    type: array
                    items:
                      $ref: ./models/publisher.v1.yaml
                  lastId:
                    type:
                      - number
                      - 'null'
              examples:
                example-1:
                  value:
                    publishers:
                      - region:
                          currency: USD
                          zone: Asia/Kolkata
                          lang: en
                          address: D-96 Flat no -112 5th Floor Munirika Village
                          city: New Delhi
                          zipcode: '110067'
                          country: IN
                        meta:
                          bank:
                            name: ''
                            ifsc: ''
                            account_no: ''
                            account_owner: ''
                          payout:
                            paypal: ''
                            payquicker: ''
                            payoneer: ''
                            paytm: alb_magji@hotmail.uk
                            mobicash: ''
                            easypaisa: ''
                          tdomain: []
                        tags:
                          - top publisher
                          - demo account
                        name: Pied Piper
                        email: subhomoy@trackier.com
                        country: IN
                        currency: INR
                        created: '2016-09-19T18:30:00.000Z'
                        modified: '2019-12-13T05:06:32.406Z'
                        username: '#PiedPiper'
                        phone: '8811576958'
                        login: '2017-10-28T06:27:06.000Z'
                        login_attempts: 1
                        manager_id: 5d25b773b6920d39cf195611
                        tier_id: 594400fa17c452060005e362
                        status: active
                        unsubscribe: false
                        signup_ip: 1.1.1.1
                        company: Pied piper
                        is_demo: false
                        macro:
                          source: '{aff_id}'
                          p1: '{transaction_id}'
                          p8: '{aff_sub8}'
                          p9: '{aff_sub9}'
                          p10: '{aff_sub10}'
                        hashId: 57c6c75934243d930c8b4581
                        id: 2
                        whitelistAdv: []
                        blockedSources:
                          - hemant_testing
                      - region:
                          currency: USD
                          zone: Asia/Kolkata
                          lang: en
                        meta:
                          payout:
                            paypal: ''
                            payquicker: ''
                            payoneer: ''
                            paytm: ''
                            mobicash: ''
                            easypaisa: ''
                        tags: []
                        name: test pub
                        email: sales@s2ssoftsys.in
                        country: IN
                        currency: INR
                        created: '2016-09-21T00:00:00.000Z'
                        modified: '2019-12-13T05:06:32.481Z'
                        username: test pub
                        phone: null
                        login: null
                        manager_id: 5d78cae3b6920d28be58cc1a
                        login_attempts: null
                        tier_id: null
                        status: deleted
                        unsubscribe: false
                        is_demo: false
                        macro:
                          p1: '{your-transaction-id}'
                          source: '{your-sub-aff-id}'
                        hashId: 57e262141d41c81f2b04b8d0
                        id: 5
                        whitelistAdv: []
                        blockedSources: []
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: ./models/error.v1.yaml
      operationId: publisher-findAll
      description: Get all publishers
      parameters:
        - schema:
            type: string
          in: header
          name: x-api-key
          description: API Key required for authentication
          required: true
        - schema:
            type: string
          in: query
          name: lastId
          description: If lastId param is present in the request then we need to send this param in the request to get the next set of rows
    post:
      summary: Create a new publisher
      operationId: publisher-create
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  publisher:
                    $ref: ./models/publisher.v1.yaml
              examples:
                example-1:
                  value:
                    publisher:
                      region:
                        currency: USD
                        zone: Asia/Kolkata
                        lang: en
                        address: D-96 Flat no -112 5th Floor Munirika Village
                        city: New Delhi
                        zipcode: '110067'
                        country: IN
                      meta:
                        bank:
                          name: ''
                          ifsc: ''
                          account_no: ''
                          account_owner: ''
                      tags:
                        - top publisher
                        - demo account
                      name: test pub
                      email: support@trackier.com
                      country: IN
                      currency: INR
                      created: '2016-09-19T18:30:00.000Z'
                      modified: '2019-12-13T05:06:32.406Z'
                      username: '#PiedPiper'
                      phone: '8811576958'
                      login: '2017-10-28T06:27:06.000Z'
                      login_attempts: 1
                      manager_id: 5d25b773b6920d39cf195611
                      tier_id: 594400fa17c452060005e362
                      status: active
                      unsubscribe: false
                      signup_ip: 1.1.1.1
                      company: Pied piper
                      is_demo: false
                      macro:
                        source: '{aff_id}'
                        p1: '{transaction_id}'
                        p8: '{aff_sub8}'
                        p9: '{aff_sub9}'
                        p10: '{aff_sub10}'
                      hashId: 57c6c75934243d930c8b4581
                      id: 2
                      whitelistAdv: []
                      blockedSources:
                        - hemant_testing
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: ./models/error.v1.yaml
              examples:
                example-1:
                  value:
                    errors:
                      - statusCode: 400
                        code: '4002'
                        codeMsg: ValidationError
                        message: Please fill the required fields
      description: Create a new publisher
      parameters:
        - schema:
            type: string
          in: header
          name: x-api-key
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
            examples:
              example-1:
                value:
                  name: hemant
                  password: '12345566'
                  email: sdfsdf22@g.com
                  phone: '123456789'
                  username: '123'
                  company: Trackier api v2
                  customFields:
                    testing: '123'
                    country: IN
        description: Data to be sent to create a new publisher
      tags:
        - Publishers
    parameters: []
  '/v2/publishers/{id}':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
        description: Publisher ID
    get:
      summary: Find Publisher by ID
      tags:
        - Publishers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  publisher:
                    $ref: '#/components/schemas/Publisher'
              examples:
                example-1:
                  value:
                    publisher:
                      region:
                        currency: USD
                        zone: Asia/Kolkata
                        lang: en
                        address: D-96 Flat no -112 5th Floor Munirika Village
                        city: New Delhi
                        zipcode: '110067'
                        country: IN
                      meta:
                        bank:
                          name: ''
                          ifsc: ''
                          account_no: ''
                          account_owner: ''
                      tags:
                        - top publisher
                        - demo account
                      name: test pub
                      email: support@trackier.com
                      country: IN
                      currency: INR
                      created: '2016-09-19T18:30:00.000Z'
                      modified: '2019-12-13T05:06:32.406Z'
                      username: '#PiedPiper'
                      phone: '8811576958'
                      login: '2017-10-28T06:27:06.000Z'
                      login_attempts: 1
                      manager_id: 5d25b773b6920d39cf195611
                      tier_id: 594400fa17c452060005e362
                      status: active
                      unsubscribe: false
                      signup_ip: 1.1.1.1
                      company: Pied piper
                      is_demo: false
                      macro:
                        source: '{aff_id}'
                        p1: '{transaction_id}'
                        p8: '{aff_sub8}'
                        p9: '{aff_sub9}'
                        p10: '{aff_sub10}'
                      hashId: 57c6c75934243d930c8b4581
                      id: 2
                      whitelistAdv: []
                      blockedSources:
                        - hemant_testing
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: ./models/error.v1.yaml
      operationId: publisher-findAll
      description: Get a single publisher
      parameters:
        - schema:
            type: string
          in: header
          name: x-api-key
          required: true
    delete:
      summary: Delete a publisher
      operationId: publisher-delete
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
              examples:
                example-1:
                  value:
                    success: true
                    message: 'Publisher Removed!'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: ./models/error.v1.yaml
      description: Delete a publisher with given ID
      parameters:
        - schema:
            type: string
          in: header
          name: x-api-key
          required: true
      tags:
        - Publishers
    post:
      summary: Edit a publisher
      operationId: publisher-edit
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  publisher:
                    $ref: ./models/publisher.v1.yaml
              examples:
                example-1:
                  value:
                    publisher:
                      region:
                        currency: USD
                        zone: Asia/Kolkata
                        lang: en
                        address: D-96 Flat no -112 5th Floor Munirika Village
                        city: New Delhi
                        zipcode: '110067'
                        country: IN
                      meta:
                        bank:
                          name: ''
                          ifsc: ''
                          account_no: ''
                          account_owner: ''
                        payout:
                          paypal: ''
                          payquicker: ''
                          payoneer: ''
                          paytm: alb_magji@hotmail.uk
                          mobicash: ''
                          easypaisa: ''
                        tdomain: []
                      tags:
                        - top publisher
                        - demo account
                      name: Pied Piper
                      email: subhomoy@trackier.com
                      country: IN
                      currency: INR
                      created: '2016-09-19T18:30:00.000Z'
                      modified: '2019-12-13T05:06:32.406Z'
                      username: '#PiedPiper'
                      phone: '8811576958'
                      login: '2017-10-28T06:27:06.000Z'
                      login_attempts: 1
                      manager_id: 5d25b773b6920d39cf195611
                      tier_id: 594400fa17c452060005e362
                      status: active
                      unsubscribe: false
                      signup_ip: 1.1.1.1
                      company: Pied piper
                      is_demo: false
                      macro:
                        source: '{aff_id}'
                        p1: '{transaction_id}'
                        p8: '{aff_sub8}'
                        p9: '{aff_sub9}'
                        p10: '{aff_sub10}'
                      hashId: 57c6c75934243d930c8b4581
                      id: 2
                      whitelistAdv: []
                      blockedSources:
                        - hemant_testing
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: ''
      description: Edit a publisher
      parameters:
        - schema:
            type: string
          in: header
          name: x-api-key
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserEdit'
            examples:
              example-1:
                value:
                  name: himanshu4
                  status: active
          application/xml:
            schema:
              type: object
              properties: {}
        description: Properties to be sent in request
      tags:
        - Publishers
  /v2/advertisers:
    get:
      summary: Find All Advertisers
      tags:
        - Advertisers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  advertisers:
                    type: array
                    items:
                      $ref: ./models/advertiser.v1.yaml
                  lastId:
                    type:
                      - 'null'
                      - integer
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/Error'
      operationId: advertiser-findAll
      description: Get 1000 advertisers in a single request then to find the next set of results pass the lastId received in the body
      parameters:
        - schema:
            type: string
          in: query
          name: lastId
    post:
      summary: Create an advertiser
      operationId: advertiser-create
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  advertiser:
                    $ref: ./models/advertiser.v1.yaml
              examples: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: ./models/error.v1.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      description: Create an advertiser
      tags:
        - Advertisers
  '/v2/advertisers/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Find a single advertiser
      tags:
        - Advertisers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  advertiser:
                    $ref: ./models/advertiser.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: ./models/error.v1.yaml
      operationId: advertiser-findOne
      description: Get a single advertiser
    post:
      summary: Update an Advertiser
      operationId: advertiser-edit
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  advertiser:
                    $ref: ./models/advertiser.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: ./models/error.v1.yaml
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserEdit'
            examples:
              example-1: {}
        description: ''
      description: Edit a single advertiser
      tags:
        - Advertisers
    delete:
      summary: Delete an Advertiser
      operationId: advertiser-delete
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: ./models/error.v1.yaml
      parameters:
        - schema:
            type: string
          in: query
          name: '{id}'
      description: Delete an advertiser
      tags:
        - Advertisers
  /v2/login:
    post:
      summary: Basic Login Endpoint
      operationId: login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      key:
                        type: string
                      user:
                        type: object
                        properties:
                          id:
                            type: integer
                          hashId:
                            type: string
                          name:
                            type: string
                          email:
                            type: string
                          username:
                            type: string
                          company:
                            type: string
                          created:
                            type: string
                          modified:
                            type: string
                      type:
                        type: string
                  success:
                    type: boolean
              examples:
                sample example:
                  value:
                    success: true
                    data:
                      key: xxxxxxxxxxxxxxxxxxxx
                      user:
                        meta:
                          afields:
                            testing: ''
                            country: IN
                        tags: []
                        username: Himanshu Tiwari
                        name: Himanshu Tiwari
                        email: mastionmind@gmail.com
                        region:
                          currency: INR
                          lang: en
                          country: IN
                          address: ''
                          state: ''
                          city: ''
                          zipcode: ''
                        unsubscribe: false
                        is_demo: false
                        macro:
                          p1: '{your-transaction-id}'
                          source: '{your-sub-aff-id}'
                        status: active
                        created: '2020-01-07T11:10:09.000Z'
                        modified: '2020-02-17T11:09:54.243Z'
                        company: Himanshu Tiwari
                        hashId: 5e146711b6920d697c4326dc
                        id: 1302
                        whitelistAdv: []
                        blockedSources: []
                      type: publisher
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: ./models/error.v1.yaml
      description: Login endpoint
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                networkUrl:
                  type: string
              required:
                - email
                - password
                - networkUrl
            examples:
              basic login example:
                value:
                  password: xxxx
                  email: xxx@gmail.com
                  networkUrl: 'http://demo.trackier.com'
      tags:
        - Network
components:
  schemas:
    UserCreate:
      title: UserCreate
      type: object
      description: ''
      x-examples:
        user create sample:
          name: Hemant
          email: hemant@gmail.com
          password: '12345678'
      properties:
        username:
          type: string
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        company:
          type: string
        phone:
          type: string
        country:
          type: string
        status:
          type: string
          enum:
            - active
            - pending
            - disabled
        region:
          type: object
          properties:
            lang:
              type: string
            currency:
              type: string
            address:
              type: string
            city:
              type: string
            state:
              type: string
            zipcode:
              type: string
        customFields:
          type: object
      required:
        - name
        - email
        - password
      x-tags:
        - Publishers
        - Advertisers
    UserEdit:
      title: UserEdit
      type: object
      x-examples:
        user edit example:
          name: Hemant
          status: pending
      properties:
        username:
          type: string
        name:
          type: string
        password:
          type: string
        email:
          type: string
          format: email
        company:
          type: string
        phone:
          type: string
        country:
          type: string
        status:
          type: string
          enum:
            - active
            - pending
            - disabled
        region:
          type: object
          properties:
            lang:
              type: string
            currency:
              type: string
            country:
              type: string
            address:
              type: string
            state:
              type: string
            city:
              type: string
            zipcode:
              type: string
        customFields:
          type: object
      x-tags:
        - Publishers
        - Advertisers
  securitySchemes:
    API Key:
      name: API Key Param
      type: apiKey
      in: query
